### ISSUE TITLE
sparse_trainers using deprecated None type behaviour, breaks jax's flatten-up

### ISSUE THREAD

**Issue by b-d-e** [google-research/jaxpruner#12]
Per Jax's error message:
```
In previous releases of JAX, flatten-up-to used to consider None to be a tree-prefix of non-None values. To obtain the previous behavior, you can usually write: jax.tree.map(lambda x, y: None if x is None else f(x, y), a, b, is_leaf=lambda x: x is None)
```

JaxPruner's sparse trainers is relying on the old version of how None should be handled, specifically within the `update_state` function. 
Support for this was removed in jaxlib version 0.4.29 (June 10, 2024) - see [changelog entry for more](https://jax.readthedocs.io/en/latest/changelog.html#jaxlib-0-4-29-june-10-2024).

Jaxpruner needs to add lambda function in sparse_trainers to handle this.

I have a fix for this implemented, will create a PR shortly.

**Comment by b-d-e** [comment]
Addressed in PR #13

**Comment by evcu** [comment]
Thanks. Sorry for the late response. I still don't know how to handle PRs with google source-of-truth and I'm low on time. Would you be okay if I did this changes on my side an pushed it? I will add your handle in the commit description for credit.

**Comment by b-d-e** [comment]
No worries - thanks for getting back on this! 

Yes of course, that is fine for both issues.

**Comment by evcu** [comment]
I had to squash the commit and forgot updating the commit message. Sorry about that.

e7af4e4 should include this change.

Thank you!
